.TH I3-PLASMA 1
.SH NAME
i3-plasma \- an IPC addon for i3
.SH SYNOPSIS
.B i3-plasma
.RB [ \-hV ]
.SH DESCRIPTION
.B i3-plasma
is an IPC addon for i3 to integrate it better with KDE plasma.
.SH OPTIONS
.TP
.B \-V, \-\-version
Print version information.
.TP
.B \-h, \-\-help
Print help information.
.SH HOMEPAGE
https://github.com/acheronfail/i3-plasma
.PP
Please report bugs and feature requests in the issue tracker.
Do your best to provide a reproducible testcase for bugs.
Also please include the version of i3-plasma, i3, plasmashell and ksmserver.
